### ISSUE TITLE
still issue with vue 2.0

### ISSUE THREAD

**Issue by rahulpatel033** [sagalbot/vue-sortable#28]
Please check my two examples.

- Using vue 1.0

http://jsbin.com/lukoxelube/edit?html,js,output

- using vue 2.0

http://jsbin.com/sozayisawi/edit?html,js,output

**Comment by MAxin521** [comment]
I have encountered this problem, how should I solve it

**Comment by rahulpatel033** [comment]
I don't know. I'm facing the same issue so I posted two examples. Hope they fixed it for newer version.

**Comment by rahulpatel033** [comment]
Fixed it.
This is the updated Bin
http://jsbin.com/vuxewidiwu/edit?html,js,output

There was a mistake. 
`<li class="list-group-item" v-for="item in lists" :key="item.key">{{ item.value }}</li>`
This is the line, where `:key` was missing. It should be there.
