### ISSUE TITLE
Sortable is not a constructor

### ISSUE THREAD

**Issue by 0xBeycan** [sagalbot/vue-sortable#43]
```javascript
import Sortable from 'vue-sortable'

Vue.use(Sortable)
```

This is how I used it and got the error in the title.

**Comment by boygiandi** [comment]
Same here

**Comment by 0xBeycan** [comment]
Dude, this plugin is for vue 1 so we get errors? I used the one below on Vue 2. So if you're using something other than vue 1, it's normal to get an error.

https://github.com/SortableJS/Vue.Draggable
